name: ✨ Feature Request
description: Suggest a new feature or enhancement for CloudPOS
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting the feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have reviewed the roadmap and documentation
          required: true
        - label: This feature aligns with CloudPOS goals and architecture
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature belong to?
      options:
        - Backend API/Services
        - Frontend UI/UX
        - Database/Data Management
        - Authentication/Security
        - Payment Processing
        - Inventory Management
        - Reporting/Analytics
        - Integration/Third-party
        - DevOps/Infrastructure
        - Mobile Support
        - Performance/Optimization
        - Documentation
        - Testing
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature request
      placeholder: Provide a clear and concise description of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or pain point this feature addresses:
        - What is the current limitation?
        - Who experiences this problem?
        - How often does this problem occur?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Provide a detailed description of how you envision this feature working:
        - User workflow
        - Technical approach
        - Integration points
        - Expected behavior
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative solutions or workarounds you've considered

  - type: textarea
    id: benefits
    attributes:
      label: Benefits and Impact
      description: What are the expected benefits of this feature?
      placeholder: |
        Describe the benefits and impact:
        - Who will benefit from this feature?
        - How will it improve the user experience?
        - What business value does it provide?
        - Performance or efficiency gains?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current usage)
        - High (Significantly improves workflow)
        - Medium (Nice to have improvement)
        - Low (Minor enhancement)
      default: 2
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Low (Small change/configuration)
        - Medium (New component/service modification)
        - High (Multiple services/major changes)
        - Very High (Architecture changes required)
        - Unknown
      default: 4

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What are the specific requirements for this feature to be considered complete?
      placeholder: |
        List specific, testable criteria:
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Provide mockups, examples, or references if applicable
      placeholder: |
        Attach mockups, screenshots, or links to examples:
        - UI mockups (drag and drop images)
        - API examples
        - Similar features in other systems
        - Reference documentation

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical considerations or constraints?
      placeholder: |
        Consider technical aspects:
        - Database schema changes
        - API changes (breaking/non-breaking)
        - Performance implications
        - Security considerations
        - Backward compatibility
        - Dependencies

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I can help with design/planning
        - label: I can help with testing
        - label: I can provide domain expertise

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request
      placeholder: Any additional information that would be helpful